import { Result } from 'better-result';
import { describe, expect, it } from 'vitest';

import { blueprint, type Blueprint } from '../blueprint/blueprint.js';
import { memoryFilePort } from '../fs/memory-file-port.js';
import { BlueprintFileUnreadable } from '../fs/read-text-file.js';
import { web } from '../resources/web.js';
import { BlueprintInvalid } from '../validation/blueprint-invalid.js';
import { checkBlueprint, type DriftReport } from './check-blueprint.js';

const api = blueprint({
  resources: [web('api', { runtime: 'node', region: 'oregon', plan: 'starter' })],
});

const generated = `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

services:
  - type: web
    name: api
    region: oregon
    plan: starter
    runtime: node
`;

const check = async (value: Blueprint, committed: string): Promise<DriftReport> => {
  const result = await checkBlueprint(value, {
    path: 'render.yaml',
    port: memoryFilePort({ files: { 'render.yaml': committed } }),
  });

  return result.unwrap('The committed file under test must be readable');
};

describe('checkBlueprint', () => {
  it('reports clean when the committed file is the one synthesize produces', async () => {
    expect((await check(api, generated)).status).toBe('clean');
  });

  it('reports clean when the committed file is reformatted but equivalent', async () => {
    const reformatted = `# someone replaced the banner
services:
    -   runtime: "node"
        name: 'api'
        plan: starter
        type: web
        region: oregon
`;

    expect((await check(api, reformatted)).status).toBe('clean');
  });

  it('reports clean when the committed file uses flow style', async () => {
    const flow = `services: [{ type: web, name: api, region: oregon, plan: starter, runtime: node }]\n`;

    expect((await check(api, flow)).status).toBe('clean');
  });

  it('reports drift with a line diff when a value changed', async () => {
    const report = await check(api, generated.replace('plan: starter', 'plan: standard'));

    expect(report.status).toBe('drift');
    if (report.status !== 'drift') return;
    expect(report.diff).toContain('-    plan: standard');
    expect(report.diff).toContain('+    plan: starter');
    expect(report.diff).toContain('@@');
  });

  it('classifies a changed runtime, region and type as immutable-field changes', async () => {
    const report = await check(
      api,
      generated.replace('runtime: node', 'runtime: python').replace('oregon', 'frankfurt'),
    );

    expect(report.status).toBe('drift');
    if (report.status !== 'drift') return;
    expect(report.immutableFieldChanges).toEqual([
      {
        section: 'services',
        resource: 'api',
        field: 'runtime',
        committed: 'python',
        generated: 'node',
      },
      {
        section: 'services',
        resource: 'api',
        field: 'region',
        committed: 'frankfurt',
        generated: 'oregon',
      },
    ]);
  });

  it('leaves immutableFieldChanges empty when only a mutable field drifted', async () => {
    const report = await check(api, generated.replace('plan: starter', 'plan: standard'));

    expect(report.status).toBe('drift');
    if (report.status !== 'drift') return;
    expect(report.immutableFieldChanges).toEqual([]);
  });

  it('reports drift when the committed file is not YAML', async () => {
    const report = await check(api, 'services: [\n  - : :\n');

    expect(report.status).toBe('drift');
    if (report.status !== 'drift') return;
    expect(report.immutableFieldChanges).toEqual([]);
  });

  it('carries the warnings of the synthesis on the report', async () => {
    const report = await check(api, generated);

    expect(report.warnings.map((warning) => warning.code)).toEqual([
      'MissingBuildCommand',
      'MissingStartCommand',
    ]);
  });

  it('reports a missing committed file as BlueprintFileUnreadable, not drift', async () => {
    const result = await checkBlueprint(api, { path: 'render.yaml', port: memoryFilePort() });

    expect(Result.isError(result)).toBe(true);
    if (!Result.isError(result)) return;
    expect(BlueprintFileUnreadable.is(result.error)).toBe(true);
    if (!BlueprintFileUnreadable.is(result.error)) return;
    expect(result.error._tag).toBe('BlueprintFileUnreadable');
    expect(result.error.path).toBe('render.yaml');
  });

  it('reads nothing when the blueprint is invalid', async () => {
    const result = await checkBlueprint(
      blueprint({ resources: [web('api', { runtime: 'node' }), web('api', { runtime: 'go' })] }),
      { path: 'render.yaml', port: memoryFilePort() },
    );

    expect(Result.isError(result)).toBe(true);
    if (!Result.isError(result)) return;
    expect(BlueprintInvalid.is(result.error)).toBe(true);
  });
});
