import { Result } from 'better-result';
import { describe, expect, it } from 'vitest';

import { blueprint, type Blueprint } from '../blueprint/blueprint.js';
import { environment } from '../blueprint/environment.js';
import { project } from '../blueprint/project.js';
import { generated } from '../env/generated.js';
import { literal } from '../env/literal.js';
import { secret } from '../env/secret.js';
import { envGroup } from '../resources/env-group.js';
import { external } from '../references/external.js';
import { keyValue } from '../resources/key-value.js';
import { postgres } from '../resources/postgres.js';
import { readReplica } from '../resources/read-replica.js';
import { staticSite } from '../resources/static-site.js';
import { web } from '../resources/web.js';
import { BlueprintInvalid } from '../validation/blueprint-invalid.js';
import { synthesize } from './synthesize.js';

const emit = (value: Blueprint): string =>
  synthesize(value).unwrap('The blueprint under test must synthesize').yaml;

describe('synthesize', () => {
  it('opens the file with the generated-file banner', () => {
    expect(emit(blueprint({ resources: [web('api', { runtime: 'node' })] }))).toBe(
      `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

services:
  - type: web
    name: api
    runtime: node
`,
    );
  });

  it('omits every key the author did not write', () => {
    expect(
      emit(blueprint({ resources: [web('api', { runtime: 'node', plan: 'starter' })] })),
    ).toContain(
      `services:
  - type: web
    name: api
    plan: starter
    runtime: node
`,
    );
  });

  it('emits the keys of a web service in one fixed order', () => {
    const api = web('api', {
      autoDeployTrigger: 'commit',
      startCommand: 'pnpm start',
      runtime: 'node',
      region: 'frankfurt',
      buildCommand: 'pnpm build',
      branch: 'main',
      repo: 'https://github.com/acme/api',
      rootDir: 'apps/api',
      healthCheckPath: '/healthz',
      preDeployCommand: 'pnpm migrate',
      plan: '1c-2g',
    });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `services:
  - type: web
    name: api
    region: frankfurt
    plan: 1c-2g
    runtime: node
    repo: https://github.com/acme/api
    branch: main
    rootDir: apps/api
    healthCheckPath: /healthz
    buildCommand: pnpm build
    startCommand: pnpm start
    preDeployCommand: pnpm migrate
    autoDeployTrigger: commit
`,
    );
  });

  it('emits the keys of a static site in one fixed order', () => {
    const site = staticSite('marketing', {
      preDeployCommand: 'pnpm sitemap',
      autoDeployTrigger: 'commit',
      domains: ['acme.com'],
      branch: 'main',
      repo: 'https://github.com/acme/marketing',
      rootDir: 'apps/marketing',
      routes: [{ type: 'rewrite', source: '/*', destination: '/index.html' }],
      headers: [{ path: '/*', name: 'X-Frame-Options', value: 'DENY' }],
      staticPublishPath: './dist',
      buildCommand: 'pnpm build',
    });

    expect(emit(blueprint({ resources: [site] }))).toContain(
      `services:
  - type: web
    name: marketing
    runtime: static
    buildCommand: pnpm build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    rootDir: apps/marketing
    repo: https://github.com/acme/marketing
    branch: main
    domains:
      - acme.com
    autoDeployTrigger: commit
    preDeployCommand: pnpm sitemap
`,
    );
  });

  it('writes no compute plan and no region for a static site', () => {
    const yaml = emit(
      blueprint({ resources: [staticSite('marketing', { staticPublishPath: './dist' })] }),
    );

    expect(yaml).not.toContain('plan:');
    expect(yaml).not.toContain('region:');
  });

  it('converts the environment map to an envVars list in declaration order', () => {
    const api = web('api', { runtime: 'node', env: { NODE_ENV: 'production', PORT: 8080 } });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
`,
    );
  });

  it('emits a preview value beside the value it overrides', () => {
    const api = web('api', {
      runtime: 'node',
      env: { LOG_FORMAT: literal('json', { previewValue: 'pretty' }) },
    });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `    envVars:
      - key: LOG_FORMAT
        value: json
        previewValue: pretty
`,
    );
  });

  it('emits a secret as sync: false and writes no value for it', () => {
    const api = web('api', { runtime: 'node', env: { STRIPE_KEY: secret() } });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `    envVars:
      - key: STRIPE_KEY
        sync: false
`,
    );
  });

  it('emits a generated value as generateValue: true and writes no value for it', () => {
    const api = web('api', { runtime: 'node', env: { SESSION_SECRET: generated() } });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `    envVars:
      - key: SESSION_SECRET
        generateValue: true
`,
    );
  });

  it('emits an imported group as a keyless fromGroup entry after the variables the map declared', () => {
    const settings = envGroup('shared-settings', { env: { LOG_LEVEL: 'info' } });
    const api = web('api', {
      runtime: 'node',
      env: { NODE_ENV: 'production' },
      envGroups: [settings],
    });

    expect(emit(blueprint({ resources: [api, settings] }))).toContain(
      `    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: shared-settings
`,
    );
  });

  it('writes no envVars key for a service that imports an empty list of groups', () => {
    const yaml = emit(blueprint({ resources: [web('api', { runtime: 'node', envGroups: [] })] }));

    expect(yaml).not.toContain('envVars');
  });

  it('writes an empty envVars list for a service whose env map is empty', () => {
    const yaml = emit(blueprint({ resources: [web('api', { runtime: 'node', env: {} })] }));

    expect(yaml).toContain('envVars: []');
  });

  it('emits an environment group under envVarGroups, after the databases', () => {
    const settings = envGroup('shared-settings', { env: { LOG_LEVEL: literal('info') } });
    const elephant = postgres('elephant', { plan: 'basic-256mb' });

    expect(emit(blueprint({ resources: [settings, elephant] }))).toContain(
      `databases:
  - name: elephant
    plan: basic-256mb
envVarGroups:
  - name: shared-settings
    envVars:
      - key: LOG_LEVEL
        value: info
`,
    );
  });

  it('emits an environment group under the environment that declares it', () => {
    const settings = envGroup('shared-settings', { env: { LOG_LEVEL: 'info' } });
    const value = blueprint({
      projects: [
        project('acme', { environments: [environment('production', { resources: [settings] })] }),
      ],
    });

    expect(emit(value)).toContain(
      `      - name: production
        envVarGroups:
          - name: shared-settings
`,
    );
  });

  it('emits an environment group under ungrouped when that is where it is declared', () => {
    const settings = envGroup('shared-settings', { env: { LOG_LEVEL: 'info' } });

    expect(emit(blueprint({ ungrouped: [settings] }))).toContain(
      `ungrouped:
  envVarGroups:
    - name: shared-settings
`,
    );
  });

  it('merges extraFields after the modeled keys', () => {
    const api = web('api', {
      runtime: 'node',
      extraFields: { maxShutdownDelaySeconds: 60, domains: ['acme.dev'] },
    });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `services:
  - type: web
    name: api
    runtime: node
    maxShutdownDelaySeconds: 60
    domains:
      - acme.dev
`,
    );
  });

  it('emits an empty document for a blueprint with no resources', () => {
    expect(emit(blueprint({}))).toBe(
      `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

{}
`,
    );
  });

  it('carries the warnings of the accepted blueprint on the report', () => {
    const result = synthesize(blueprint({ resources: [web('api', { runtime: 'node' })] }));

    expect(Result.isOk(result)).toBe(true);
    if (!Result.isOk(result)) return;
    expect(result.value.warnings.map((warning) => warning.code)).toEqual([
      'MissingBuildCommand',
      'MissingStartCommand',
    ]);
  });

  it('emits a database under databases, never under services', () => {
    expect(emit(blueprint({ resources: [postgres('elephant')] }))).toBe(
      `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

databases:
  - name: elephant
`,
    );
  });

  it('emits the keys of a database in one fixed order', () => {
    const elephant = postgres('elephant', {
      readReplicas: [readReplica('elephant-replica')],
      highAvailability: { enabled: true },
      diskSizeGB: 35,
      user: 'elephant_user',
      postgresMajorVersion: '17',
      plan: 'basic-1gb',
      region: 'frankfurt',
      databaseName: 'elephant',
      ipAllowList: [{ source: '203.0.113.4/30', description: 'office' }],
    });

    expect(emit(blueprint({ resources: [elephant] }))).toContain(
      `databases:
  - name: elephant
    databaseName: elephant
    user: elephant_user
    region: frankfurt
    plan: basic-1gb
    diskSizeGB: 35
    postgresMajorVersion: "17"
    highAvailability:
      enabled: true
    ipAllowList:
      - source: 203.0.113.4/30
        description: office
    readReplicas:
      - name: elephant-replica
`,
    );
  });

  it('quotes the major version, because Render reads it as a string', () => {
    expect(
      emit(blueprint({ resources: [postgres('elephant', { postgresMajorVersion: '18' })] })),
    ).toContain('postgresMajorVersion: "18"');
  });

  it('emits an empty ipAllowList, which tells Render to allow no external connection', () => {
    expect(emit(blueprint({ resources: [postgres('elephant', { ipAllowList: [] })] }))).toContain(
      `  - name: elephant
    ipAllowList: []
`,
    );
  });

  it('emits a database reference as a fromDatabase entry', () => {
    const elephant = postgres('elephant');
    const api = web('api', { runtime: 'node', env: { DATABASE_URL: elephant.connectionString } });

    expect(emit(blueprint({ resources: [api, elephant] }))).toContain(
      `    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: elephant
          property: connectionString
`,
    );
  });

  it('references a read replica by its own name', () => {
    const replica = readReplica('elephant-replica');
    const elephant = postgres('elephant', { readReplicas: [replica] });
    const api = web('api', { runtime: 'node', env: { REPLICA_URL: replica.connectionString } });

    expect(emit(blueprint({ resources: [api, elephant] }))).toContain(
      `      - key: REPLICA_URL
        fromDatabase:
          name: elephant-replica
          property: connectionString
`,
    );
  });

  it('emits a service property reference as a fromService entry', () => {
    const auth = web('auth', { runtime: 'node' });
    const api = web('api', { runtime: 'node', env: { AUTH_HOSTPORT: auth.hostport } });

    expect(emit(blueprint({ resources: [api, auth] }))).toContain(
      `    envVars:
      - key: AUTH_HOSTPORT
        fromService:
          type: web
          name: auth
          property: hostport
`,
    );
  });

  it('emits an aliased variable as a fromService entry naming the key', () => {
    const auth = web('auth', { runtime: 'node', env: { ROOT_PASSWORD: 'set-in-dashboard' } });
    const api = web('api', { runtime: 'node', env: { PASSWORD: auth.envVar('ROOT_PASSWORD') } });

    expect(emit(blueprint({ resources: [api, auth] }))).toContain(
      `      - key: PASSWORD
        fromService:
          type: web
          name: auth
          envVarKey: ROOT_PASSWORD
`,
    );
  });

  it('emits a self-reference through the callback form of env', () => {
    const api = web('api', {
      runtime: 'node',
      env: (self) => ({ APP_HOST: self.renderVar('RENDER_EXTERNAL_HOSTNAME') }),
    });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `      - key: APP_HOST
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_HOSTNAME
`,
    );
  });

  it('emits a reference to a resource outside this blueprint like any other', () => {
    const api = web('api', {
      runtime: 'node',
      env: { AUTH_HOSTPORT: external.privateService('legacy-auth').hostport },
    });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `      - key: AUTH_HOSTPORT
        fromService:
          type: pserv
          name: legacy-auth
          property: hostport
`,
    );
  });

  it('emits a Key Value connection string with the type Render reserves for it', () => {
    const cache = keyValue('cache', { ipAllowList: [] });
    const api = web('api', { runtime: 'node', env: { CACHE_URL: cache.connectionString } });

    expect(emit(blueprint({ resources: [api, cache] }))).toContain(
      `      - key: CACHE_URL
        fromService:
          type: keyvalue
          name: cache
          property: connectionString
`,
    );
  });

  it('emits the keys of a Key Value instance in one fixed order', () => {
    const cache = keyValue('cache', {
      persistenceMode: 'snapshot',
      plan: '1g',
      maxmemoryPolicy: 'volatile-ttl',
      region: 'frankfurt',
      ipAllowList: [{ source: '203.0.113.4/30', description: 'office' }],
    });

    expect(emit(blueprint({ resources: [cache] }))).toContain(
      `services:
  - type: keyvalue
    name: cache
    region: frankfurt
    ipAllowList:
      - source: 203.0.113.4/30
        description: office
    plan: 1g
    maxmemoryPolicy: volatile-ttl
    persistenceMode: snapshot
`,
    );
  });

  it('emits a Key Value instance under services, never under databases', () => {
    const emitted = emit(blueprint({ resources: [keyValue('cache', { ipAllowList: [] })] }));

    expect(emitted).toContain('services:');
    expect(emitted).not.toContain('databases:');
  });

  it('emits an empty ipAllowList on a Key Value instance, which allows no connection', () => {
    expect(emit(blueprint({ resources: [keyValue('cache', { ipAllowList: [] })] }))).toContain(
      `  - type: keyvalue
    name: cache
    ipAllowList: []
`,
    );
  });

  it('emits services before databases', () => {
    const elephant = postgres('elephant');
    const emitted = emit(blueprint({ resources: [elephant, web('api', { runtime: 'node' })] }));

    expect(emitted.indexOf('services:')).toBeLessThan(emitted.indexOf('databases:'));
  });

  it('emits nothing when validation fails', () => {
    const result = synthesize(
      blueprint({ resources: [web('api', { runtime: 'node' }), web('api', { runtime: 'go' })] }),
    );

    expect(Result.isError(result)).toBe(true);
    if (!Result.isError(result)) return;
    expect(BlueprintInvalid.is(result.error)).toBe(true);
    expect(result.error.issues.map((issue) => issue.code)).toEqual(['DuplicateResourceName']);
  });
  it('emits the root previews ahead of the resources', () => {
    expect(
      emit(
        blueprint({
          previews: { generation: 'automatic', expireAfterDays: 7 },
          resources: [web('api', { runtime: 'node' })],
        }),
      ),
    ).toContain(
      `previews:
  generation: automatic
  expireAfterDays: 7
services:
  - type: web
    name: api
    runtime: node
`,
    );
  });

  it('omits the root previews the author did not write', () => {
    expect(emit(blueprint({ resources: [web('api', { runtime: 'node' })] }))).not.toContain(
      'previews:',
    );
  });

  it('emits a project as its environments and their resources', () => {
    const api = web('api', { runtime: 'node' });
    const staging = web('api-staging', { runtime: 'node' });

    expect(
      emit(
        blueprint({
          projects: [
            project('acme', {
              environments: [
                environment('production', { resources: [api] }),
                environment('staging', { resources: [staging] }),
              ],
            }),
          ],
        }),
      ),
    ).toContain(
      `projects:
  - name: acme
    environments:
      - name: production
        services:
          - type: web
            name: api
            runtime: node
      - name: staging
        services:
          - type: web
            name: api-staging
            runtime: node
`,
    );
  });

  it("emits an environment's networking and permissions after its resources", () => {
    expect(
      emit(
        blueprint({
          projects: [
            project('acme', {
              environments: [
                environment('production', {
                  resources: [web('api', { runtime: 'node' })],
                  networking: { isolation: 'enabled' },
                  permissions: { protection: 'disabled' },
                }),
              ],
            }),
          ],
        }),
      ),
    ).toContain(
      `        networking:
          isolation: enabled
        permissions:
          protection: disabled
`,
    );
  });

  it('emits the ungrouped resources under their own key', () => {
    expect(emit(blueprint({ ungrouped: [web('docs', { runtime: 'node' })] }))).toContain(
      `ungrouped:
  services:
    - type: web
      name: docs
      runtime: node
`,
    );
  });

  it('omits an empty project list and an empty ungrouped list', () => {
    const emitted = emit(blueprint({ resources: [web('api', { runtime: 'node' })] }));

    expect(emitted).not.toContain('projects:');
    expect(emitted).not.toContain('ungrouped:');
  });

  it('merges the root extraFields after the modeled root keys', () => {
    expect(
      emit(
        blueprint({
          resources: [web('api', { runtime: 'node' })],
          extraFields: { version: '1' },
        }),
      ),
    ).toContain(
      `services:
  - type: web
    name: api
    runtime: node
version: "1"
`,
    );
  });

  it('reports a resource value placed in two locations rather than emitting it twice', () => {
    const api = web('api', { runtime: 'node' });
    const result = synthesize(
      blueprint({
        resources: [api],
        projects: [
          project('acme', { environments: [environment('production', { resources: [api] })] }),
        ],
      }),
    );

    expect(Result.isError(result)).toBe(true);
    if (!Result.isError(result)) return;
    expect(result.error.issues.map((issue) => issue.code)).toEqual(['ResourceInMultipleLocations']);
  });

  it('warns about a pinned branch while root previews are on', () => {
    const result = synthesize(
      blueprint({
        previews: { generation: 'automatic' },
        resources: [
          web('api', {
            runtime: 'node',
            branch: 'main',
            buildCommand: 'pnpm build',
            startCommand: 'pnpm start',
          }),
        ],
      }),
    );

    expect(Result.isOk(result)).toBe(true);
    if (!Result.isOk(result)) return;
    expect(result.value.warnings.map((warning) => warning.code)).toEqual([
      'BranchDisablesPreviews',
    ]);
  });

  it('emits a database placed in an environment under that environment', () => {
    const value = blueprint({
      projects: [
        project('acme', {
          environments: [
            environment('production', {
              resources: [web('api', { runtime: 'node' }), postgres('elephant')],
            }),
          ],
        }),
      ],
    });

    expect(emit(value)).toContain(
      `      - name: production
        services:
          - type: web
            name: api
            runtime: node
        databases:
          - name: elephant
`,
    );
  });

  it('emits a database placed in the ungrouped list under ungrouped', () => {
    const value = blueprint({ ungrouped: [postgres('elephant')] });

    expect(emit(value)).toContain(
      `ungrouped:
  databases:
    - name: elephant
`,
    );
  });
});
