import { Result } from 'better-result';
import { describe, expect, it } from 'vitest';

import { blueprint, type Blueprint } from '../blueprint/blueprint.js';
import { web } from '../resources/web.js';
import { BlueprintInvalid } from '../validation/blueprint-invalid.js';
import { synthesize } from './synthesize.js';

const emit = (value: Blueprint): string =>
  synthesize(value).unwrap('The blueprint under test must synthesize').yaml;

describe('synthesize', () => {
  it('opens the file with the generated-file banner', () => {
    expect(emit(blueprint({ resources: [web('api', { runtime: 'node' })] }))).toBe(
      `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

services:
  - type: web
    name: api
    runtime: node
`,
    );
  });

  it('omits every key the author did not write', () => {
    expect(
      emit(blueprint({ resources: [web('api', { runtime: 'node', plan: 'starter' })] })),
    ).toContain(
      `services:
  - type: web
    name: api
    plan: starter
    runtime: node
`,
    );
  });

  it('emits the keys of a web service in one fixed order', () => {
    const api = web('api', {
      autoDeployTrigger: 'commit',
      startCommand: 'pnpm start',
      runtime: 'node',
      region: 'frankfurt',
      buildCommand: 'pnpm build',
      branch: 'main',
      repo: 'https://github.com/acme/api',
      rootDir: 'apps/api',
      healthCheckPath: '/healthz',
      preDeployCommand: 'pnpm migrate',
      plan: '1c-2g',
    });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `services:
  - type: web
    name: api
    region: frankfurt
    plan: 1c-2g
    runtime: node
    repo: https://github.com/acme/api
    branch: main
    rootDir: apps/api
    healthCheckPath: /healthz
    buildCommand: pnpm build
    startCommand: pnpm start
    preDeployCommand: pnpm migrate
    autoDeployTrigger: commit
`,
    );
  });

  it('converts the environment map to an envVars list in declaration order', () => {
    const api = web('api', { runtime: 'node', env: { NODE_ENV: 'production', PORT: 8080 } });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
`,
    );
  });

  it('merges extraFields after the modeled keys', () => {
    const api = web('api', {
      runtime: 'node',
      extraFields: { maxShutdownDelaySeconds: 60, domains: ['acme.dev'] },
    });

    expect(emit(blueprint({ resources: [api] }))).toContain(
      `services:
  - type: web
    name: api
    runtime: node
    maxShutdownDelaySeconds: 60
    domains:
      - acme.dev
`,
    );
  });

  it('emits an empty document for a blueprint with no resources', () => {
    expect(emit(blueprint({}))).toBe(
      `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

{}
`,
    );
  });

  it('carries the warnings of the accepted blueprint on the report', () => {
    const result = synthesize(blueprint({ resources: [web('api', { runtime: 'node' })] }));

    expect(Result.isOk(result)).toBe(true);
    if (!Result.isOk(result)) return;
    expect(result.value.warnings.map((warning) => warning.code)).toEqual([
      'MissingBuildCommand',
      'MissingStartCommand',
    ]);
  });

  it('emits nothing when validation fails', () => {
    const result = synthesize(
      blueprint({ resources: [web('api', { runtime: 'node' }), web('api', { runtime: 'go' })] }),
    );

    expect(Result.isError(result)).toBe(true);
    if (!Result.isError(result)) return;
    expect(BlueprintInvalid.is(result.error)).toBe(true);
    expect(result.error.issues.map((issue) => issue.code)).toEqual(['DuplicateResourceName']);
  });
});
