import { Result } from 'better-result';
import { describe, expect, it } from 'vitest';

import { blueprint, type Blueprint } from '../blueprint/blueprint.js';
import type { BuildFilter } from '../resources/build-filter.js';
import { envGroup } from '../resources/env-group.js';
import { web, type WebConfig } from '../resources/web.js';
import { synthesize } from '../synth/synthesize.js';
import { BlueprintInvalid } from '../validation/blueprint-invalid.js';
import { validate } from '../validation/validate.js';
import type { ResourceDefaults } from './resource-defaults.js';
import { withDefaults } from './with-defaults.js';

// SAFETY: JSON.parse returns any. The record below stands in for a defaults scope the CLI loaded
// through Node type stripping, which erases types without checking them.
const unchecked: (json: string) => ResourceDefaults = JSON.parse;
const uncheckedWeb: (json: string) => WebConfig = JSON.parse;

const emit = (value: Blueprint): string =>
  synthesize(value).unwrap('The blueprint under test must synthesize').yaml;

describe('withDefaults', () => {
  it('returns the same factory set the library exports', () => {
    const scope = withDefaults({ region: 'oregon' });

    expect(Object.keys(scope).sort()).toEqual([
      'cron',
      'envGroup',
      'keyValue',
      'postgres',
      'privateService',
      'staticSite',
      'web',
      'withDefaults',
      'worker',
    ]);
  });

  it('hands back the bare factory for the kind that takes no default', () => {
    expect(withDefaults({ region: 'oregon' }).envGroup).toBe(envGroup);
  });

  it('emits a defaulted value exactly as the author-written one', () => {
    const scoped = withDefaults({
      region: 'frankfurt',
      repo: 'https://github.com/acme/mono',
      branch: 'main',
      plan: { web: 'standard' },
    }).web('api', { runtime: 'node', startCommand: 'pnpm start' });

    const written = web('api', {
      runtime: 'node',
      region: 'frankfurt',
      plan: 'standard',
      repo: 'https://github.com/acme/mono',
      branch: 'main',
      startCommand: 'pnpm start',
    });

    expect(emit(blueprint({ resources: [scoped] }))).toBe(
      emit(blueprint({ resources: [written] })),
    );
  });

  it('lets the value on the resource win over the scope', () => {
    const scope = withDefaults({ region: 'frankfurt', plan: { web: 'standard' } });

    expect(scope.web('api', { runtime: 'node', region: 'ohio' }).config).toMatchObject({
      region: 'ohio',
      plan: 'standard',
    });
  });

  it('lets an inner scope win over an outer one', () => {
    const team = withDefaults({ region: 'frankfurt', repo: 'https://github.com/acme/mono' });
    const app = team.withDefaults({ region: 'singapore' });

    expect(app.web('api', { runtime: 'node' }).config).toMatchObject({
      region: 'singapore',
      repo: 'https://github.com/acme/mono',
    });
  });

  it('keeps the region and the plan of a static site out of the emitted document', () => {
    const scope = withDefaults({
      region: 'frankfurt',
      repo: 'https://github.com/acme/mono',
      plan: { web: 'standard' },
    });

    expect(
      emit(blueprint({ resources: [scope.staticSite('site', { buildCommand: 'pnpm build' })] })),
    ).toBe(
      `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

services:
  - type: web
    name: site
    runtime: static
    buildCommand: pnpm build
    repo: https://github.com/acme/mono
`,
    );
  });

  it('keeps the repository fields of a datastore out of the emitted document', () => {
    const scope = withDefaults({
      region: 'frankfurt',
      repo: 'https://github.com/acme/mono',
      branch: 'main',
      rootDir: 'apps/api',
      plan: { keyValue: 'starter', postgres: 'basic-256mb' },
    });

    const emitted = emit(
      blueprint({
        resources: [scope.keyValue('cache', { ipAllowList: [] }), scope.postgres('records')],
      }),
    );

    expect(emitted).toContain('region: frankfurt');
    expect(emitted).not.toContain('repo:');
    expect(emitted).not.toContain('branch:');
    expect(emitted).not.toContain('rootDir:');
  });

  it('keeps a repository default off an image-sourced service', () => {
    const scope = withDefaults({ repo: 'https://github.com/acme/mono', branch: 'main' });

    const emitted = emit(
      blueprint({
        resources: [scope.worker('jobs', { runtime: 'image', image: { url: 'acme/jobs:1.4.0' } })],
      }),
    );

    expect(emitted).toContain('url: acme/jobs:1.4.0');
    expect(emitted).not.toContain('repo:');
    expect(emitted).not.toContain('branch:');
  });

  it('synthesizes a base scope an inner scope overrides without a warning', () => {
    const team = withDefaults({
      region: 'frankfurt',
      repo: 'https://github.com/acme/mono',
      branch: 'main',
    });
    const preview = team.withDefaults({ branch: 'preview' });
    const report = synthesize(
      blueprint({
        resources: [
          preview.web('api', {
            runtime: 'node',
            buildCommand: 'pnpm build',
            startCommand: 'pnpm start',
          }),
        ],
      }),
    ).unwrap('The blueprint under test must synthesize');

    expect(report.warnings).toEqual([]);
  });

  it('takes a record the type stripping could not check', () => {
    // @ts-expect-error a JavaScript caller can call withDefaults with no record at all.
    expect(() => withDefaults()).not.toThrow();
    expect(() => withDefaults(unchecked('null'))).not.toThrow();
    expect(() => withDefaults(unchecked('{ "plan": null }'))).not.toThrow();
  });

  it('treats a record it cannot read as an empty one', () => {
    const scope = withDefaults(unchecked('null')).withDefaults(unchecked('{ "plan": null }'));

    expect(scope.web('api', { runtime: 'node' }).config).toEqual({ runtime: 'node' });
  });

  it('carries every default the resource could take, landed or overridden', () => {
    const scope = withDefaults({ region: 'frankfurt', repo: 'https://github.com/acme/mono' });

    expect(scope.web('api', { runtime: 'node', region: 'ohio' }).defaults).toEqual({
      scopes: [{ keys: ['region', 'repo'] }],
      eligible: ['region', 'repo'],
      applied: [{ key: 'repo', field: 'repo', scope: { keys: ['region', 'repo'] } }],
    });
  });

  it('carries no eligibility for a field the kind does not have', () => {
    const scope = withDefaults({ region: 'frankfurt', repo: 'https://github.com/acme/mono' });

    expect(scope.staticSite('site', { buildCommand: 'pnpm build' }).defaults?.eligible).toEqual([
      'repo',
    ]);
  });

  it('freezes the declaration and the keys it holds', () => {
    const declaration = withDefaults({ region: 'frankfurt' }).web('api', { runtime: 'node' })
      .defaults?.scopes[0];

    expect(declaration?.keys).toEqual(['region']);
    expect(Object.isFrozen(declaration)).toBe(true);
    expect(Object.isFrozen(declaration?.keys)).toBe(true);
  });

  it('carries the scopes that created a resource, outer first', () => {
    const team = withDefaults({ region: 'frankfurt' });
    const app = team.withDefaults({ repo: 'https://github.com/acme/mono' });

    expect(app.web('api', { runtime: 'node' }).defaults?.scopes).toEqual([
      { keys: ['region'] },
      { keys: ['repo'] },
    ]);
  });

  it('attributes a default to the innermost scope that declared it', () => {
    const team = withDefaults({ region: 'frankfurt' });
    const app = team.withDefaults({ region: 'singapore' });
    const provenance = app.web('api', { runtime: 'node' }).defaults;

    expect(provenance?.applied).toEqual([
      { key: 'region', field: 'region', scope: { keys: ['region'] } },
    ]);
    expect(provenance?.applied[0]?.scope).toBe(provenance?.scopes[1]);
  });

  it('fills the build filter, the deploy trigger and the allow list a scope declares', () => {
    const scope = withDefaults({
      autoDeployTrigger: 'checksPass',
      buildFilter: { paths: ['apps/**'] },
      ipAllowList: [{ source: '203.0.113.0/24', description: 'office' }],
    });

    expect(scope.web('api', { runtime: 'node' }).config).toEqual({
      runtime: 'node',
      autoDeployTrigger: 'checksPass',
      buildFilter: { paths: ['apps/**'] },
      ipAllowList: [{ source: '203.0.113.0/24', description: 'office' }],
    });
  });

  it('writes an object default by reference and replaces it whole', () => {
    const filter: BuildFilter = { paths: ['apps/**'] };
    const scope = withDefaults({ buildFilter: filter });

    expect(scope.web('api', { runtime: 'node' }).config.buildFilter).toBe(filter);
    expect(
      scope.web('api', { runtime: 'node', buildFilter: { ignoredPaths: ['docs/**'] } }).config
        .buildFilter,
    ).toEqual({ ignoredPaths: ['docs/**'] });
  });

  it('lets an inner scope win on one object key and inherit the other', () => {
    const team = withDefaults({
      autoDeployTrigger: 'off',
      buildFilter: { paths: ['apps/**'] },
    });
    const app = team.withDefaults({ buildFilter: { paths: ['apps/checkout/**'] } });

    expect(app.worker('jobs', { runtime: 'node' }).config).toEqual({
      runtime: 'node',
      autoDeployTrigger: 'off',
      buildFilter: { paths: ['apps/checkout/**'] },
    });
  });

  it('keeps a build filter and a deploy trigger off an image-sourced service', () => {
    const scope = withDefaults({
      autoDeployTrigger: 'checksPass',
      buildFilter: { paths: ['apps/**'] },
    });

    const emitted = emit(
      blueprint({
        resources: [scope.worker('jobs', { runtime: 'image', image: { url: 'acme/jobs:1.4.0' } })],
      }),
    );

    expect(emitted).toContain('url: acme/jobs:1.4.0');
    expect(emitted).not.toContain('buildFilter');
    expect(emitted).not.toContain('autoDeployTrigger');
  });

  it('never raises BuildFilterOnImageSource from a scope default', () => {
    const scope = withDefaults({ buildFilter: { paths: ['apps/**'] } });
    const report = synthesize(
      blueprint({
        resources: [
          scope.web('api', { runtime: 'image', image: { url: 'acme/api:1.4.0' } }),
          scope.privateService('inner', { runtime: 'image', image: { url: 'acme/inner:1' } }),
          scope.worker('jobs', { runtime: 'image', image: { url: 'acme/jobs:1' } }),
          scope.cron('nightly', {
            runtime: 'image',
            schedule: '0 3 * * *',
            image: { url: 'acme/nightly:1' },
          }),
        ],
      }),
    ).unwrap('The blueprint under test must synthesize');

    expect(report.warnings.map((warning) => warning.code)).not.toContain(
      'BuildFilterOnImageSource',
    );
  });

  it('keeps an allow list off the kinds whose schema lacks the field', () => {
    const scope = withDefaults({ ipAllowList: [{ source: '203.0.113.0/24' }] });

    expect(scope.worker('jobs', { runtime: 'node' }).config).toEqual({ runtime: 'node' });
    expect(scope.cron('nightly', { runtime: 'node', schedule: '0 3 * * *' }).config).toEqual({
      runtime: 'node',
      schedule: '0 3 * * *',
    });
  });

  it('leaves the required allow list of a Key Value store to the store', () => {
    const scope = withDefaults({ ipAllowList: [{ source: '203.0.113.0/24' }] });
    const store = scope.keyValue('cache', { ipAllowList: [] });

    expect(store.config.ipAllowList).toEqual([]);
    expect(store.defaults?.eligible).toEqual([]);
  });

  it('fills the allow list of a static site and of a database', () => {
    const scope = withDefaults({ ipAllowList: [{ source: '203.0.113.0/24' }] });

    expect(scope.staticSite('site', { buildCommand: 'pnpm build' }).config.ipAllowList).toEqual([
      { source: '203.0.113.0/24' },
    ]);
    expect(scope.postgres('records').config.ipAllowList).toEqual([{ source: '203.0.113.0/24' }]);
  });

  it('carries the new keys among the eligible and the applied ones', () => {
    const scope = withDefaults({
      autoDeployTrigger: 'checksPass',
      buildFilter: { paths: ['apps/**'] },
      ipAllowList: [],
    });
    const provenance = scope.web('api', { runtime: 'node', autoDeployTrigger: 'off' }).defaults;

    expect(provenance?.eligible).toEqual(['autoDeployTrigger', 'buildFilter', 'ipAllowList']);
    expect(provenance?.applied.map((entry) => entry.key)).toEqual(['buildFilter', 'ipAllowList']);
  });

  it('leaves no provenance on a resource a bare factory made', () => {
    expect(web('api', { runtime: 'node' }).defaults).toBeUndefined();
  });

  it('says where the value came from when a default fails the kind schema', () => {
    const scope = withDefaults(unchecked('{ "region": "oregn" }'));
    const result = validate(blueprint({ resources: [scope.web('api', { runtime: 'node' })] }));

    expect(Result.isError(result)).toBe(true);

    if (Result.isError(result)) {
      expect(BlueprintInvalid.is(result.error)).toBe(true);
      expect(result.error.issues).toEqual([
        {
          code: 'InvalidConfig',
          at: { resource: 'api', field: 'region' },
          message: expect.stringContaining('takes "region" from a defaults scope'),
        },
      ]);
    }
  });

  it('says where the value came from when a default fails inside an object', () => {
    const scope = withDefaults(unchecked('{ "buildFilter": { "paths": "apps/**" } }'));
    const result = validate(blueprint({ resources: [scope.web('api', { runtime: 'node' })] }));

    expect(Result.isError(result)).toBe(true);

    if (Result.isError(result)) {
      expect(BlueprintInvalid.is(result.error)).toBe(true);
      expect(result.error.issues).toEqual([
        {
          code: 'InvalidConfig',
          at: { resource: 'api', field: 'buildFilter.paths' },
          message: expect.stringContaining('takes "buildFilter" from a defaults scope'),
        },
      ]);
    }
  });

  it("says nothing about a scope on an issue the resource's own value raised", () => {
    const scope = withDefaults({ region: 'frankfurt' });
    const result = validate(
      blueprint({
        resources: [scope.web('api', uncheckedWeb('{ "runtime": "node", "region": "oregn" }'))],
      }),
    );

    if (Result.isError(result)) {
      expect(result.error.issues[0]?.message).not.toContain('defaults scope');
    }
  });
});
