import { Result } from 'better-result';
import { describe, expect, it } from 'vitest';

import { blueprint } from '../blueprint/blueprint.js';
import { web } from '../resources/web.js';
import { BlueprintInvalid } from '../validation/blueprint-invalid.js';
import { memoryFilePort } from './memory-file-port.js';
import { writeBlueprint } from './write-blueprint.js';
import { BlueprintWriteFailed } from './write-text-file.js';

const api = blueprint({ resources: [web('api', { runtime: 'node' })] });

describe('writeBlueprint', () => {
  it('writes the synthesized document at the requested path', async () => {
    const port = memoryFilePort();
    const result = await writeBlueprint(api, { path: 'infra/render.yaml', port });

    expect(Result.isOk(result)).toBe(true);
    expect(port.files.get('infra/render.yaml')).toBe(
      `# Generated by render-blueprint. Do not edit this file by hand.
# Edit the TypeScript blueprint that produced it and synthesize again.

services:
  - type: web
    name: api
    runtime: node
`,
    );
  });

  it('reports the path it wrote and the warnings of the blueprint', async () => {
    const result = await writeBlueprint(api, { path: 'render.yaml', port: memoryFilePort() });

    expect(Result.isOk(result)).toBe(true);
    if (!Result.isOk(result)) return;
    expect(result.value.path).toBe('render.yaml');
    expect(result.value.warnings.map((warning) => warning.code)).toEqual([
      'MissingBuildCommand',
      'MissingStartCommand',
    ]);
  });

  it('replaces the text already at the path', async () => {
    const port = memoryFilePort({ files: { 'render.yaml': 'services: []\n' } });
    await writeBlueprint(api, { path: 'render.yaml', port });

    expect(port.files.get('render.yaml')).toContain('name: api');
  });

  it('writes nothing when the blueprint is invalid', async () => {
    const port = memoryFilePort();
    const result = await writeBlueprint(
      blueprint({ resources: [web('api', { runtime: 'node' }), web('api', { runtime: 'go' })] }),
      { path: 'render.yaml', port },
    );

    expect(Result.isError(result)).toBe(true);
    if (!Result.isError(result)) return;
    expect(BlueprintInvalid.is(result.error)).toBe(true);
    expect(result.error._tag).toBe('BlueprintInvalid');
    expect(port.files.size).toBe(0);
  });

  it('names the failed path in BlueprintWriteFailed when the writer refuses', async () => {
    const port = memoryFilePort({ unwritablePaths: ['render.yaml'] });
    const result = await writeBlueprint(api, { path: 'render.yaml', port });

    expect(Result.isError(result)).toBe(true);
    if (!Result.isError(result)) return;
    expect(BlueprintWriteFailed.is(result.error)).toBe(true);
    if (!BlueprintWriteFailed.is(result.error)) return;
    expect(result.error._tag).toBe('BlueprintWriteFailed');
    expect(result.error.path).toBe('render.yaml');
    expect(result.error.message).toContain('render.yaml');
  });
});
